---

- block:
    - name: "try new ssh key type: {{ item }}"
      set_fact:
        ssh_pubkey: "{{ default_ssh_basedir.rstrip('/') }}/id_{{ item }}.pub"

    - name: check wheter public key exists
      stat:
        path: "{{ ssh_pubkey }}"
      register: ssh_pubkey_st
    
    - name: change control variable when key is found   
      set_fact:
        key_exists: yes
      when: ssh_pubkey_st.stat.exists
  when: not key_exists