---

# Display one own public IP cidr block, when not found just show public IP.

- hosts: localhost 
  tasks:
    - file:
        path: "{{ cache_dir }}"
        state: directory

    - include_role:
        name: my_pub_cidr
    
    - debug:
        var: my_cidr