---

- hosts: localhost
  tasks:
    - include_role:
        name: vars_helper

    - include_role:
        name: aws_config
      vars: 
        config: "{{ sim_deployer_config }}"

- import_playbook: vpn-border.yml
  when: is_vpn_operator
  tags:
    - vpn-border

- hosts: localhost
  tasks:
    # uses cross-platform ssh agent to handle adding private keys
    - name: ensure ansible finds ssh configurations at runtime
      shell: ssh-add $(ls {{ default_ssh_dir | expanduser }}/id_* | egrep -v ".pub$")

- import_playbook: wireguard.yml
  when: is_vpn_operator
  tags:
    - wireguard
  