---

- hosts: localhost
  tasks:
    - include_role:
        name: vars_helper

    - include_role:
        name: aws_config
      vars: 
        config: "{{ sim_deployer_config }}"

- import_playbook: vpn-border.yml
  when: is_vpn_operator
  tags:
    - vpn-border

- hosts: localhost
  vars:
    ssh_dir: "{{ '~/.ssh' | expanduser }}"
  tasks:
    - name: ensure destination ssh directory exists
      file:
        path: "{{ ssh_dir }}"
        state: directory

    # ugly!
    - name: ensure ansible finds ssh configurations at runtime
      shell: find {{ default_ssh_dir | expanduser }} -exec cp -r '{}' {{ ssh_dir }} \; 

- import_playbook: wireguard.yml
  when: is_vpn_operator
  tags:
    - wireguard
  