---

- hosts: localhost
  environment:
    AWS_DEFAULT_REGION: "{{ inst_region }}"
  
  tasks:
    - include_role:
        name: aws_config
      vars: 
        config: "{{ sim_deployer_config }}"

    - set_fact:
        vpn_server_instance: "{{ instance_state | default('present') }}"

    - name: ensure vpn server instance is {{ vpn_server_instance }}
      ec2:
        instance_ids: "{{ instance_ids | default(omit) }}" 
        image: "{{ image_id }}"
        instance_type: t2.micro
        key_name: "{{ key_id }}"
        group_id: "{{ sg_ids | first }}"
        wait: true
        state: "{{ vpn_server_instance }}"
        count: "{{ vpn_instances_count }}"
      register: vpn_server_inst

    - block:
      - name: gather all attached network interfaces
        ec2_eni_info:
          filters:
            attachment.instance-id: "{{ vpn_server_inst.instance_ids }}"
        register: attached_netifs

      - name: allocate an elastic ip for each created instance 
        ec2_eip:
          in_vpc: true
          device_id: "{{ item.id }}"
          # reuse_existing_ip_allowed: "{{ reuse_existing_ip | default(True) }}"
        with_items:
          - "{{ attached_netifs.network_interfaces }}"
      when: vpn_server_inst.changed

    - name: execute post-create role
      include_role:
        name: post-instance-create
      vars:
        inst_id: "{{ item.id }}" 
        inst_ip: "{{ item.public_ip }}"
        host_group: vpn_servers
      with_items:
        - "{{ vpn_server_inst.instances }}"
    