---

- hosts: vpn_servers
  vars:
    _server_index: 0
    local_basedir: client-configs
  tasks:
    - name: update server packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: change server hostname
      hostname:
        name: vpn-server{{ _server_index }}

    - set_fact:
        _server_index: "{{ _server_index + 1 }}"

    - name: disable X11Forwarding in ssh daemon config
      replace:
        dest: /etc/ssh/sshd_config
        regexp: '^X11Forwarding yes'
        replace: X11Forwarding no
      register: disable_ssh_x11forwarding

    - name: reload ssh daemon
      service:
        name: sshd
        state: reloaded
      when: disable_ssh_x11forwarding.changed

    - include_role:
        name: wireguard/server
      tags:
        - vpn-server

    
    