version: '3'

services:
  setup:
    build:
      context: .
      dockerfile: Dockerfile.setup
    volumes:
      - ./keys/manager:${DOCKER_ANS_MANAGER_KEYS_VOLUME}
      - ./keys/deployer:${DOCKER_ANS_DEPLOYER_KEYS_VOLUME}
      
      - ./ansible:${DOCKER_ANS_ANSIBLE_VOLUME}:ro
      - ./.vars/:${DOCKER_ANS_VARS_VOLUME}
      - ./.controls:${ANSIBLE_LOCKPATH}
    container_name: setup
    command: -c run_manager
    env_file:
      - .env

  deployer:
    depends_on:
      - setup
    volumes:
      - ./keys/deployer:${DOCKER_ANS_DEPLOYER_KEYS_VOLUME}
      - ./ansible:${DOCKER_ANS_ANSIBLE_VOLUME}:ro
      - ./.vars/:${DOCKER_ANS_VARS_VOLUME}
      - ./.controls:${ANSIBLE_LOCKPATH}
    build:
      context: .
      dockerfile: Dockerfile.deployer
    container_name: deployer
    command: -c run_deployer
    env_file:
      - .env